UBUNTU: SAUCE: [arm] fixup __aeabi_uldivmod undefined build error
When building on arm we run into the following build error due to
gcc-4.6 optimizing do_div into a uldivmod call:

ERROR: "__aeabi_uldivmod" [drivers/scsi/megaraid/megaraid_sas.ko] undefined!

Inline some assembly to prevent the compiler optimization.

Signed-off-by: Leann Ogasawara <leann.ogasawara@canonical.com>